install(
    FILES ClockSource.hpp
          CommonBlocks.hpp
          ConverterBlocks.hpp
          DataSink.hpp
          FunctionGenerator.hpp
          PythonBlock.hpp
          PythonInterpreter.hpp
          Selector.hpp
          SignalGenerator.hpp
          StreamToDataSet.hpp 
          SyncBlock.hpp
          Trigger.hpp
    DESTINATION ${GR_INCLUDE_DIR}/gnuradio-4.0/basic)